name: Deploy Static Website to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AKIARGA7ZUOL4VGCPCE5 }}
          aws-secret-access-key: ${{ secrets.yeMzKLEK2KwpRLQLnuXonBDii5XULGISgrOYYs6i }}
          aws-region: ap-south-1

      # Step 3: Deploy website files to S3
      - name: Deploy to S3
        run: |
          aws s3 sync . s3://${{ secrets.gitaction-app1 }} --delete \
            --exclude ".git/*" \
            --exclude ".github/*"
